version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/spring-boot
    
    steps:
      # git pull
      - checkout

      # setup testing env
      - setup_remote_docker
            
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKER_USERNAME" "$DOCKER_PASSWORD"
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          
      - run:
          name: Build Docker Image
          command: docker build --no-cache -t $DOCKER_USERNAME/spring-boot .
          
      - run:
          name: Push Image to DockerHub
          command: docker push $DOCKER_USERNAME/spring-boot